import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Nav from "@/components/Nav"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Aman Portfolio",
  description: "Generated by create next app",
  icons:{
    icon: "/batmanreal.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <link rel="icon" type="image/png" sizes="32x32" href="/whiteBatman.png" /> 
      </head>
      <body className={inter.className}>
        <Nav/>
        {children}
      </body>
    </html>
  );
}
